version: '3.8'

services:
  api:
    build:
      context: ./BalatroPoker.Api
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    networks:
      - balatro-network

  frontend:
    build:
      context: ./BalatroPoker
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - api
    environment:
      - API_BASE_URL=http://api:8080
    networks:
      - balatro-network

networks:
  balatro-network:
    driver: bridge